basePath: /api/v1
definitions:
  internal.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  service.FileSourcePager:
    properties:
      pageCount:
        type: integer
      sources:
        items:
          $ref: '#/definitions/service.FileSourceResp'
        type: array
      total:
        type: integer
    type: object
  service.FileSourceResp:
    properties:
      cold_backups:
        type: integer
      data_cid:
        type: string
      file_name:
        type: string
      file_size:
        type: integer
      hot_backups:
        type: integer
      ipfs_urls:
        items:
          type: string
        type: array
      not_found_provider:
        type: string
      providers:
        items:
          $ref: '#/definitions/service.ProviderInfo'
        type: array
      rebuild_status:
        type: boolean
      status:
        type: string
    type: object
  service.ProviderInfo:
    properties:
      provider_id:
        type: string
      status:
        type: string
    type: object
  service.SummaryResp:
    properties:
      cids_count:
        type: integer
      data_stored:
        type: integer
      deals_count:
        type: integer
      height:
        type: integer
      ipfs_nodes:
        type: integer
      providers:
        type: integer
    type: object
host: http://rebuilder.fogmeta.com/
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  title: ReBuilder API
  version: "1.0"
paths:
  /cid/{cid}:
    get:
      parameters:
      - description: ID
        in: path
        name: cid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Response'
      summary: Retrieve file storage from filecoin to ipfs based on cid
  /files:
    get:
      parameters:
      - description: data_cid/file_name
        in: query
        name: field_name
        type: string
      - description: Page number, starting from 0 by default
        in: query
        name: page
        type: integer
      - description: By default, there are 20 lines.
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.FileSourcePager'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Response'
      summary: Get a list of file storage information
  /retrieve:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.Response'
      summary: retrieve file
  /summary:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.SummaryResp'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal.Response'
      summary: Summary information display
  /upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal.Response'
      summary: upload file
swagger: "2.0"
